### PR TITLE
update JDepend from fork, fixing various undetected package cycles

### PR DESCRIPTION
**Pull request by BenRomberg**

### CODE REVIEW

**Comment by marcphilipp** [comment]
Looks good to me, thanks! :+1: 

Have you asked for permission from your employer to "publish" those two class files?

**Comment by BenRomberg** [comment]
Yes, it's not an issue.

Unfortunately I failed to reproduce the failing package cycle detection using dummy classes. It seems to be related to a fancy edge case that is quite uncommon, and not to any specific feature of the Java language.

Btw, I've released these changes on Maven Central myself in the meantime and added another convenience feature (showing 2-edged nested cycles right away, which is a good starting point when trying to break down larger cycles) - see https://github.com/BenRomberg/no-package-cycles-enforcer-rule.

**Comment by marcphilipp** [comment]
Sounds good to me! I'm not sure how to proceed, though. Do you want to continue working in and releasing your fork? Or would it make sense to merge your changes into this repo and release that?

**Comment by BenRomberg** [comment]
Not sure either, I just wanted to make sure those changes are available on Maven Central, as I'm using the Rule in quite a few projects nowadays, and it's always easier to remove the cycles earlier than later. Wasn't sure anyone would respond to the PR, let alone merge it and file another release ;-)

Either way is fine for me.

**Comment by BenRomberg** [comment]
After some more discussion offline we decided not to merge this PR.

**Pull request closed without merging**
