### PR TITLE
Allow to specify packages to include/exclude.

### PR DESCRIPTION
**Pull request by SimY4**
Some libraries like bean-validation rely on strong package dependencies. For these exceptional cases, I would like to be able to exclude them from the analysis.

### CODE REVIEW

**Comment by SimY4** [comment]
Is this repo still maintained?

**Comment by davidburkhart** [comment]
Thank you for the contribution. I was considering this feature by myself long time ago, but found ways around it (by fixing the cycles :wink:).
I don't completely understand your point about "strong package dependencies", as that does not mean cyclic! Also why should bean-validation introduce cycles to your project?
Also would moving those beans into a separate maven module without cycle check be an option?
Don't get me wrong, I am not completely unwilling to merge you request. But introducing a backdoor always intruiges to bypass the problems instead of fixing them from start. If exclusions or inclusions are non-empty, shouldn't there be a warning in the build log?

**Comment by SimY4** [comment]
Hi David,

Thank you for reviewing this PR.

I understand your point of being principled on this. But I can give you a few cases where exclusions will be useful:

 - in some cases where projects are big and full of legacy, it’s better to introduce such rules Incrementally, fixing cycles and then enforcing the rule on fixed code paths.
 - when the dirty hack is required to address the critical issue. It's better to give the option to disable certain rules for small part or your program than demand all-or-nothing semantic.

I agree on having warning logs for ignored packages. I’ll address this soon.

**Comment by davidburkhart** [comment]
@SimY4 Thanks for the contribution, I just published release 1.0.9!

**Pull request merged**
